name: Déploiement GitHub Pages

on:
  push:
    branches:
      - main  # Déclenché uniquement sur la branche main
  workflow_dispatch:  # Permet le déclenchement manuel

# Définir les permissions nécessaires pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# N'autoriser qu'un seul déploiement à la fois
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construction et déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Uploader le dossier public
          path: './public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
